### ISSUE TITLE
Domain specific strapidata d fetch

### ISSUE THREAD

**Issue by mpennaste** [poff-bnff/web2021#120]
Probleem:
Hetkel source/strapidata/ kausta fetchitakse domeenipõhised YAMLid.

Kui a_fetchi me enam targeted build'ide puhul ei kasuta, siis peaks hoidma strapidatas kogu infot mida Strapi lifecycle pidevalt uuendab, samas ülejäänutele scriptidele oleks hea kui nad saaksid kasutada buildi ajal juba eelnevalt domeenipõhiselt filtreeritud infot nagu ennegi.

Minu mõte asub harus Domain-specific-Strapidata-d_fetch:
Mingi vahekiht mis filtreerib targeted buildi alguses enne teisi skripte mittevajaliku välja.
Näiteks antud harus tõstsin a_fetchist domeenikontrolli ümber d_fetchi (jah, C jäi vahele, D nagu Domain, aga saab ümber nimetada).
Lisaks muutsin source/strapidata/ ümber source/_allStrapidata/ (alakriips minumeelest on parem, saab kohe ülaltpoolt kätte) ning tekitasin uue kausta source/_domainStrapidata/.

Jooksutades a_fetchi tõmmatakse kogu Strapist tulev data source/_allStrapidata/
Jooksutades d_fetchi (hetkel kirjutage käsitsi domeeni sisse) loetakse kogu source/_allStrapidata/ sisu, filterdatakse domeeni järgi ja asetatakse tulemus source/_domainStrapidata/ kausta. Oma arvutis võtab d_fetch ca 3,5 sec.

Vabalt võib olla paremaid mõtteid, aga see üks võimalus, et targeted buildis enam vähem kiirelt just konkreetsele domeenile vajalik teistele scriptidele ette sööta.

**Comment by LiisKasper** [comment]
Strapist tulevatel objektidel pole kõigil domeeni küljes, Saaks tekitada mapingu läbi eraldi faili aga see tähendab faili pidevat uuendamist või mudeli lukku panemist ja lõplikku korrastamist. Või tuleb igale objektile külge panna tema domeen (või märksõna 'full' vms).

**Comment by mitselek** [comment]
mulle tundub selline vahekiht täiesti mõistlik

**Comment by mpennaste** [comment]
Main'is ja serveris tänasest
