### ISSUE TITLE
domeenide konsolideerimine

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#13]
strapi ja ssg ja veeb asub nüüd kõik ühes masinas: 167.71.59.228
- a.hoff.ee suunatakse admin.poff.ee
- hoff.ee tuleb kataloogist /srv/www/hoff.ee
- build.hoff.ee tuleb /srv/ssg/build/hoff.ee

todo:
1. PÖFFi githubi workflow, mis praegu publitseerib inscaping -> zone, peab sama soojaga kopeerima inscaping -> /srv/www/poff.ee;
2. PÖFFi minibuild hakkab ehitama /srv/ssg/build/poff.ee;
3. Strapi deploy plugina nupp kopeerib /srv/ssg/build/_domeeninimi_ -> /srv/www/_domeeninimi_

Mart aitab ja õpetab, kuidas me saame ise need paganama serdid ja nginx ja muu maagia - https://docs.google.com/spreadsheets/d/1s5xa5tOqaM0VEg8KKTtiDIs3Ojqprom486ltnCTxBK0/edit?usp=sharing

**Comment by LiisKasper** [comment]
Sama Kumu ja Filmikooli lehe kohta:
- kumu.poff.ee tuleb kataloogist /srv/www/kumu.poff.ee
- build.kumu.ee tuleb /srv/ssg/build/kumu (ilma .ee, entule ei meeldi)
- filmikool.poff.ee tuleb kataloogist /srv/www/filmikool.poff.ee
- build.filmikool.ee tuleb /srv/www/build/filmikool (ilma .ee, entule ei meeldi)
