### ISSUE TITLE
ssg-serve on rivist väljas

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#18]
sest build kataloog sisaldab punkti
`build/hoff.ee`

**Comment by mpennaste** [comment]
ssg\helpers\name_build_directory.js toimetab vastavalt ssg\domain_specifics.yaml:
ehk build kataloogi nimes ei ole enam punkti:
  poff.ee: poff
  justfilm.ee: justfilm
  kinoff.poff.ee: kinoff
  industry.poff.ee: industry
  shorts.poff.ee: shorts
  hoff.ee: hoff
  kumu.poff.ee: kumu
  tartuff.ee: tartuff
