### ISSUE TITLE
domain name should be set in env

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#251]
for example:
- https://github.com/poff-bnff/web2021/blob/strapi.pennaste.eu-to-dev.poff.ee/ssg/source/login/index.pug#L18
- https://github.com/poff-bnff/web2021/blob/strapi.pennaste.eu-to-dev.poff.ee/ssg/source/login/script.js#L43
- https://github.com/poff-bnff/web2021/blob/strapi.pennaste.eu-to-dev.poff.ee/ssg/source/login/script.js#L111
- https://github.com/poff-bnff/web2021/blob/strapi.pennaste.eu-to-dev.poff.ee/ssg/source/login/script.js#L286
- https://github.com/poff-bnff/web2021/blob/main/ssg/helpers/build_manager.js#L20
- https://github.com/poff-bnff/web2021/blob/main/ssg/helpers/strapiQuery.js#L7
- https://github.com/poff-bnff/web2021/blob/main/ssg/helpers/strapiAuth.js#L7
- https://github.com/poff-bnff/web2021/blob/main/strapi/strapi-development/admin/src/components/LeftMenu/LeftMenuHeader/index.js#L3
- ...

**Comment by mitselek** [comment]
.strapienv

export StrapiPassword='************'
export StrapiUserName='************'
export StrapiHost='dev.poff.ee'
export StrapiProtocol='https'
export StrapiPort='1337'

**Comment by mpennaste** [comment]
Uued ja vanad vajalikud keskkonnamuutujad:

StrapiPassword
StrapiUserName
StrapiHost
StrapiProtocol
StrapiPort
StrapiColour

StrapiDatabaseHost
StrapiDatabasePort
StrapiDatabaseName
StrapiDatabaseUsername
StrapiDatabasePassword
