### ISSUE TITLE
user persons -> user profile

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#278]

**Comment by mitselek** [comment]
``` sql
update public."users-permissions_user"
set user_profile = users_person
```

**Comment by mpennaste** [comment]
`INSERT INTO public.user_profiles ("id", "user", "firstName", "lastName", "gender", "address", "birthdate", "email", "phoneNr", "created_by", "updated_by", "created_at", "updated_at")
SELECT "id", "users_permissions_user", "firstName", "lastName", "gender", "address", "birthdate", "email", "phoneNr", "created_by", "updated_by", "created_at", "updated_at" from public.users_persons;`

Kustutasin õhtul tabeli ja tegin ise ka läbi. Lisaks suunasin ka kasutajate pildid uuele collectionile.
