### ISSUE TITLE
Filmid ja seansside listi PUG

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#309]
Palun filmide listi (search film) ja screeningute listi (search screening) PUGi / yaml'isse (nagu praegu on programmid)
- Countries
- Directors

E palun võimalust ka riike ja režissööre ses listi vaates iga filmi juures näidata
Mis lõpuks välja kommenteerime - otsustame

**Comment by mitselek** [comment]
Jaan Leppik  10:30 AM
> vaatan, et see on kah juba live läinud, et filmdel on listi vaates rež ja riik
> aga kole suure vahega on need
> palun kommenteerime need praegi välja, teeme enne vahed väiksemaks, kui LIVE paneme

Mihkel Putrinš  10:39 AM
> no ma heidan korra pilgu CSS'ile pigem

**Comment by mitselek** [comment]
mulle näib, et probleemi lahendab, kui siin
https://github.com/poff-bnff/web2021/blob/7bb417a47f552e4af99119428640db3ab64ed9fc/ssg/source/_styles_templates/_styles_poff/style.styl#L1951-L1954

muuta `grid-gap 2rem` -> `grid-gap: 0rem 2rem`
