### ISSUE TITLE
Kasseti templeidile uued rollid ja subtiitrid

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#333]
Ühe- ja mitmefilmi kassettidel tarvis näidata suve jooksul juurde tulnud rolle, selleks

- [x]  templeidil luua uued plokid
- [x] strapis kirjeldada vastavad labelid https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::label-group.label-group/2

**Comment by jaanleppik** [comment]
Näide: Film VIIMANE VÕIMALUS
