### ISSUE TITLE
Kasseti tasemel keeli kuvame. Vaja on supakaid ka

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#334]
- [ ] https://github.com/poff-bnff/web2021/blob/295a734415e29a80aaa160d784336f27f7930fee/ssg/source/_templates/cassette_templates/cassette_poff_multiple_films_template.pug#L622-L631
- [ ] https://github.com/poff-bnff/web2021/blob/295a734415e29a80aaa160d784336f27f7930fee/ssg/source/_templates/cassette_templates/cassette_poff_single_film_template.pug#L245-L254

**Comment by LiisKasper** [comment]
Vastavad muudatused on serveris.
