### ISSUE TITLE
Programm / film -> PresentedBy organistasioonide järjekord

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#339]
Praegu tundub presentedBy prganisatsioonide järjekord olevat tähestiku järjekord.

Keiss: 
Lisan Programmi või filmi alla PresentedBy moodulisse organisatsiooni yhes järjekorras, e selles järjekorras, nagu tahan, et need lehel oleks, aga need järjestatakse peale salvestamist tähestiku järjekorda ja ka näidatakse lehel tähestiku järjekorras. 

Kas ainuls võimalus on lisada ORDER väli iga org juurde ses PresentedBy moodulis? Ja lisamise järjekorda me kätte ei saa?

**Comment by mpennaste** [comment]
Minuteada ilma ei saa jah järjekorda neil - Strapi ilmselt tagastab kuidas ise heaks arvab.
