### ISSUE TITLE
https://blacknightsfilmfestival.com sert aegunud

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#352]
Kas me saame selle serdi uuendada?

https://blacknightsfilmfestival.com

**Comment by mitselek** [comment]
võibla peaks suunama pigem https://poff.ee/en/leht peale?

**Comment by mpennaste** [comment]
> võibla peaks suunama pigem https://poff.ee/en/leht peale?

Kui on blacknightsfilmfestival.com/en/leht, siis suunab
