### ISSUE TITLE
Vialogi embed code update

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#359]
Vialog, e videomessaging rakndus, mis meil filmide lehtedel toiminud n, vajab koodiuuendust.

Näide kõikide vestluste lehe kohta on siin:
For example on the https://poff.ee/letschat page you need to start using the new embed code:
<a name="vialog-UZB5T141"></a><script async src="https://ui.vialog.app/vialog-loader.js" data-vialog="UZB5T141"></script>

Juhend, millest esimene punkt käi koodi uuendamise kohta, on siin:
https://vialog.app/how-to-update-the-tool

Filmide lehtedel on hetkel see kood välja kommenteeritud. 

Kus see letschat leht / lehe kood asub - alles otsin.

**Comment by LiisKasper** [comment]
Kui vaadata vialogi [lehte](https://docs.google.com/spreadsheets/d/1dtOou5vrBNgG6HBtEULXjmzcTrOlRkKojmCiMVuF06M/edit#gid=0), siis seal kaks esimest filmi olemas, nii, et url on igal real unique (tekib tulpa E, vastuolu, kaks ühesugust id), kas see on tulemus mida ootad? @jaanleppik

**Comment by jaanleppik** [comment]
nyyd võiks filmi pug'is vialog'i koodi sisse kommenteerida taas.
Ega ses üpetuses selle filmi lehel oleva iframe koodi osa muutusest juttu polnud? et peaks toimima sellisena, nagu möödunud aastal oli? ainult sisse kommenteerida?

**Comment by mpennaste** [comment]
Tegelen.
Sellisena ilmselt ei toimi kui eelnev aasta, st kood muutunud, aga tegelen ja panen näituseks devi ehitama vaatamiseks.

**Comment by mpennaste** [comment]
https://build.dev.poff.ee/film/18-khz/
Ei kipu töötama filmi Strapi IDga praegu. Tabelis ka näen, et vist polegi veel neid UniqueIDsid loodud?

`a(name=`vialog-${film.id}`)
script(async src='https://ui.vialog.app/vialog-loader.js' data-vialog=film.id)`

**Comment by jaanleppik** [comment]
nyyd on need unique ID'd loodud tabelis. 
Kuidas me need omale salvestame...? ma sain jah nyyd aru, et me peame kasutama nende loodud unikaalseid IDsid, lisaks oma filmi IDäle.
näide:
nende unikaalne # name: 5wjj65pf
embed code, kus sees see nende loodud unikaalne kood:
<a name="5wjj65pf"></a><script async src="https://ui.vialog.app/vialog-loader.js" data-vialog-partner="poff25" data-vialog-topic="2924" data-lang="en"></script>

ja seal siis topid=meie filmi id strapis. 

E kuidas me saame need tabelisse genereeritud ID'd kätte, nii, et me saame iga filmi juures neid kasutada?
Kas see ongi sul Martin juba tehtud, et saad buildimise ajal need kaks unikaalset kokku panna iga filmi lehel vialogi moodulit ehitades: meie strapi id ja nende unikaalse name id?

**Comment by mitselek** [comment]
[Strapis](https://admin.poff.ee/admin/plugins/content-type-builder/content-types/application::film.film) on filmi juures väli `vialog_id`.
- [ ] lisada `vialog_id` ka andmemudelisse
