### ISSUE TITLE
Screeningu tabelist Strapisse uuesti saatmisel ei uuendata ticketingURL'i

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#362]
[Screeningu tabel](https://docs.google.com/spreadsheets/d/18TDGnMwdIdmifsptQaKQ_0n4L6tqxxKEqj8Smfcbt_k/edit#gid=1327096495)
muudan ära ticketingURLi, ticketing ID muutmise kaudu, ja saadan uuesti seansi strpisse - aga ticketing URL ri muutu. 
Kas see on sellepärast, et tegelikult teda uuesti ei kirjutatagi, kuna ID on sama ja omeas jne?

**Comment by LiisKasper** [comment]
Ticketing URL tabelis muutub automaatselt, kui ticketing ID. Probleem tekib siis, kui uus info ei jõua Strapisse, 
Kuna screening objekt Strapis sisaldab mitut UID välja siis probleem tekib meil seal.
Remote id on nüüd iga kord, ise tekitatud random nr. Eelmisel aastal sisaldas Eventival id, kuna sellel aastal ei kasuta siis võib see random nr seal olla, ei sega.
UID väli on ka ticketingId ja selle muutmine tabelist tekitab segaduse. Kui sama Id on Strapis juba samal väljal olemas siis seda uuesti Strapisse ei kirjutata. (Nt püüad kahel objektil id vahetada, siis peab enne ühe(1) id ära kustutama ja teisel(2) selle lisama ja siis esimesele(1) lisama teise(2) id. Sama tabeli puhul, enne tuleb Strapist id ära kustutada )

**Comment by mitselek** [comment]
### [Strapi:Screenings](https://admin.poff.ee/admin/plugins/content-type-builder/content-types/application::screening.screening)
- [ ] remoteId
  kas kustutada? unikaalsust mite nõuda?
- [ ] ticketingId ja ticketingURL
  kas tegu võib olla andmeliiasusega?
