### ISSUE TITLE
IndustryPerson objetile lisada festivalEdition relatsioon

### ISSUE THREAD

**Issue by LiisKasper** [poff-bnff/web2021#371]
Industry_person objektile on vaja lisada festivalEdition, et eristada erinevate aastate Industry inimesi.
Olemas on: Strapis Industry_person objektis, väljas festival_editions, relatsioon objektile festivalEdition.
Git master harus meie datamodelisse lisatud vajalikud muudatused, a_fetch töötab.
pull request #370

Martin, võta üle! :)

**Comment by mpennaste** [comment]
Industry persons are now filtered by active_industry_editions listed in domain_specifics and affected pages (ex: /featured-persons) built accordingly including only people who have at least one festival_edition assigned and present in domain_specifics.active_industry_editions.
**Note:** Currently there are no industry_persons with festival_edition assigned in Strapi.
