### ISSUE TITLE
Eventivali login / INDUSTRY / ja selle parameetrite üle vaatamine

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#375]
Peak tegema koosoleku / arutelu et yle vaadata, kuidas meil Eventivali login töötab ja kuidas me saame piirata, millised inimesed Evetivaliga sisse logida saavad.

Kas homme, neljapäeval, 4. nov mingi aeg sobiks?
alates lõunast?

**Comment by LiisKasper** [comment]
Mina olen homme (4. nov) olemas.

**Comment by mitselek** [comment]
@Martin Pennaste ***@***.***> võiks ka olla - mis kellast Sa
jõuaksid?
Mulle sobiks mida varem, seda parem aga saan päeva sättida.
Kell kolm on mul üks tunnine zoom.

mihkel
5656 0978

**Comment by mpennaste** [comment]
Ca lõunast kolmeni peaks sobima. Kus, kontoris või veebis?

**Comment by jaanleppik** [comment]
Teeks kontoris

**Comment by mitselek** [comment]
- [ ] @mpennaste vajab EV badge'i
- [ ] lambda kood vaja strapi juurde tõsta - SUUR tükk!

**Comment by mitselek** [comment]
Jaan Leppik  10:51 PM
> tehke omale mõned kontod siis nii:
> 
> Minge vp.eventival.com/poff 
> Konto loomiseks vajutage “Continue with Eventival” ja siis avanevalt lehelt “Create a new account”, täitke kohustuslikud andmed. 
> Pärast emaili verifitseerimist minge tagasi vp.eventival.com/poff ja täitke veel kohustuslikke välju nagu pilt jne. 
> Kui see on tehtud, siis on konto olemas.
> 
> siis on nii, nagu kõigil, ja saab ka konto loomisel kasutatud meilide toimimist testida: õiget ja vale pärast

**Comment by LiisKasper** [comment]
Liis Käsper Nov 10th at 2:20 PM
tähelepanekud Eventialiga sisse logides:
5 replies

Liis Käsper  1 day ago
Palusin end sisse logida Eventival konto kaudu. Tegin läbi kaks korda. Poffi kodulehe pilt ei muutunud (ette jäi sisselogimise leht). Mingit teadet ei tulnud ...
2 files 
![Screenshot from 2021-11-10 14-20-17](https://user-images.githubusercontent.com/68702810/141449951-f9acd978-f414-4a23-ab96-3f77f96062aa.png)
![Screenshot from 2021-11-10 14-23-13](https://user-images.githubusercontent.com/68702810/141449986-85dcda46-6bb3-4384-a0db-9b47c88c1548.png)

Liis Käsper  1 day ago
Läksin ikka kodulehele kolama, et kas saan lisad midagi lemmikuks vms. Palub sisse logida, et saakin filmi lemmikuks panna, mis õige. Aga minu pöff menüü punktis kirjas tere ja võimalus välja logida
![Screenshot from 2021-11-10 14-25-09](https://user-images.githubusercontent.com/68702810/141450122-99d9003a-6ae6-435c-adc2-f2c1402f129a.png)

Liis Käsper  1 day ago
enda profiili vaadates on e-post undefined
![Screenshot from 2021-11-10 14-27-32](https://user-images.githubusercontent.com/68702810/141450194-a57fd218-7591-4650-8338-b58a8a047ea6.png)

Liis Käsper  1 day ago
Parem näide olukorras kus olin just enda arust Eventivaliga sisse loginud (edited) 
![Screenshot from 2021-11-10 14-29-09](https://user-images.githubusercontent.com/68702810/141450223-57ffe31f-56ad-4bc1-bae0-8ae3a9febd27.png)

Martin Pennaste  1 day ago
Ma kahtlustran, et pead mõnda muud e-maili kasutama kas spreadsheeti tarbeks või siis logimiseks. Spreadsheeti kasutajaga vb sisse saab, aga nagu näha ei toimi kindlasti kõik nii nagu peaks :slightly_smiling_face: Ma enda pennaste04@gmail kasutajat vahepeal viskan maintenance all, vahepeal authenticated alla, vastavalt olukorrale :smile: (edited) 
image.png 
image.png

**Comment by mpennaste** [comment]
Siin on Industry teema tegelikult mitte PÖFF. PÖFFi peaks vist kõik kel Eventivali konto, ligi pääsema. Industry'le aga vaid valitud.

**Comment by LiisKasper** [comment]
Kustutasin Strapis USER'i spreadsheet, mille e-post liis,kasper@poff.ee
proovin uuesti sisse logida eventivali kontoga (mille e-post liis.kasper@poff.ee) 
ja sellel korral sisselogimine õnnestus, profiili täitmine ja lemmikute lisamine jne ka.

**Comment by mpennaste** [comment]
Tundub, et siis läks õnneks :)

**Comment by LiisKasper** [comment]
Jah, sain, minu viga, testime Industry lehte. 
Sain sisse ka Industry lehele :)

**Comment by mpennaste** [comment]
Fixed by #424
