### ISSUE TITLE
Transaction'i payment info komponendi asemel lapikuks

### ISSUE THREAD

**Issue by mpennaste** [poff-bnff/web2021#378]
- [x] Mudeli muudatus Strapis (@mitselek)
- [x] Mudeli muudatus saata serverist main harusse (@mpennaste)
- [x] Koodimuudatus ja testimine (testost) (@mpennaste)
- [x] Kood live ja full build poff.ee (@mpennaste)
- [x] Komponendi andmete kopeerimine uutesse väljadesse vahetult kui uus kood live jõuab (@mitselek / @LiisKasper ?)
- [x] Google sheet tabelites korrektuurid? (@mitselek / @LiisKasper ?)

**Comment by LiisKasper** [comment]
Komponendi andmete kopeerimine uutesse väljadesse vahetult kui uus kood live jõuab (@mitselek / @LiisKasper ?) 
Lahendus issues #295

**Comment by mpennaste** [comment]
Muudatus live.
Payment komponendi võib transactioni alt (ja kui mujal ei kasutata, üldse) kustutada.

**Comment by LiisKasper** [comment]
Google sheet tabelites korrektuurid? (@mitselek / @LiisKasper ?) 
Paralleelselt on avatud uus issue #398, mis tundub lahendavat ka antud punkti. 
Issue  #398

**Comment by LiisKasper** [comment]
``` sql
SELECT * 
FROM public.transactions as trans
left join public.transactions_components as trans_c
	on trans.id = trans_c.transaction_id
order by "dateTime" ASC
```
Päringu vastuse vaatlus kinnitab, et kasutuses on lapik versioon.
Kustuta Strapis ja andmebaasis payment komponent trasactioni seest ja eraldiseisva komponendina. @LiisKasper

**Comment by LiisKasper** [comment]
Payment konmponent on kustutatud Strapis transaction seest ja eraldiseisvana. Lisaks andmebaasist.
