### ISSUE TITLE
asenda screeningMode eventMode'ga

### ISSUE THREAD

**Issue by LiisKasper** [poff-bnff/web2021#380]
kaob ära collection screeningMode, tuleb asemele eventMode. 
Tee vajalikud asendused koodis

**Comment by LiisKasper** [comment]
- [ ] Uus collection Strapisse
- [ ] lisa väärused onsite, online, hybrid Strapis
- [ ] Uus collection mudelisse
- [ ] main
- [ ] Õigused eventMode collectionile
- [ ] Vajalikud muudatused koodis

**Comment by mpennaste** [comment]
Pull request #383 

@LiisKasper Screeningu all näen ikka screening_mode, seal siis peaks ka võtma event_mode kasutusele, siis arvan võib pull requesti maini saata.

**Comment by LiisKasper** [comment]
Jah, ei kustutanud enne ära kui kõik muudatused tehtud.

- [ ] Kustuta screeningMode andmebaasist ja mudelitest

**Comment by LiisKasper** [comment]
Koodi muudatused on jäänud vist poolikuks, kustutasin hommikul screeningMode Strapist ja meie mudelist. Ja bulid error.
Muutsin kolmes ssg/helpers/fetch_ ... koodis minimodelis screeningMode, eventMode vastu. 
@mpennaste build töötab, aga palun kontrolli, et kood ikka teeb vajalikud sammud, frondi jaoks vms.
pull request #391

**Comment by LiisKasper** [comment]
Ok, nüüd saan aru, et räägime üksteisest mööda. Ma sain aru, et teed muudatused ja paned live. Ma ei registreerinud kohe ära, et pull request on üleval ja vaja live saata. Minu viga!
