### ISSUE TITLE
Eventival login: kasutaja info tuvastamine

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#387]
mida me teada saame eventivaliga login'i tehes?
kas saame:
Akrediteeringu tyybi / nimetuse?
Akre kehtivuse kuupäevad?

Ja siis saame selle alusel näidata vi mitte näidata lehti, nagu möödunud aastal? 
E meil on list akrediteeringutest: nende tyypidest - nimi ja / või ID
võrdleme end autentiva kasutaja akrediteeringut selle nimekirja vastu ja kontrollime akre kehtivuse kuupäevi
ja näitame lehti ja lkahtede osi?

**Comment by mpennaste** [comment]
Palun mitte teha topelt-issue'sid
#78 
#375
