### ISSUE TITLE
muutub eventMode objekti kuju

### ISSUE THREAD

**Issue by LiisKasper** [poff-bnff/web2021#392]
Nii meie mudelis, kui [Strapis](https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::event-mode.event-mode?page=1&pageSize=10&_sort=name:ASC) on objekt EventMode nüüd kujul:
EventMode:
    name_private: (text)
    name_et: text
    name_en: text
    name_ru: text

Enne: 
EventMode:
    name: (text)

Tehtud:
objekti muudatus
Strapis name välja sisu tõstetud name_private välja sisse

Vaja teha:

- [x] tõlkeväljad on vaja täita (name_et, name_en, name_ru) @jaanleppik 
- [x] vajalikud muudatused koodis @mpennaste (kui on vaja)

**Comment by mpennaste** [comment]
Kuna hetkel ei kasuta mujal kui User-my_events harus (ja seal on kõik uue muudatuse järgi), siis rohkem koodis muuta vajalikuks ei pea (kuna see igalpool niikuinii välja kommenteeritud).

**Comment by jaanleppik** [comment]
Event_Mode on industry_event'i juures nyyd kasutusel sh eventide listi vaates.
