### ISSUE TITLE
Industry Festival editioni põhine fetch: Industry_People ja Industry_Projects jah

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#393]
Industry lehel oleks vaja lisaks Industry_Eventidele fetchida ka Industry_People ja Industry_Projects festival editioni põhiselt (Industry@Tallinn 2021).

Kas see panna kah domain specificusse?

Samal ajal on meil industry Projects ka aastast 2005, mida samuti, teises valikus, peaks saama lehel näha. 
Sa Martin oled sell eolukorra juba vist lahendanud? Et selleks on teine fetch?

**Comment by mpennaste** [comment]
@jaanleppik 

Industry projects arhiivileht on olemas ja live, sama fetcher toimetab aga arhiiviasjad eraldi failidesse ning projektide leht kuvab ainult DOMAIN_SPECIFICS.active_industry_editions määratud editioniga projekte. Arhiivileht kuvab kõiki teisi.
https://github.com/poff-bnff/web2021/pull/306

Inustry persoonid samuti filtreeritakse.
https://github.com/poff-bnff/web2021/pull/374
