### ISSUE TITLE
Passi ostude tabel ei anna uut infot

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#398]
Passi ostude tabel (ei pane siis avalikuks linki igaks juhuks) ei uuene, e ei anna alates 4. nv enam uute sotude infot ja tehingute sheet lausa tyhi. 
Lakkas töötamast umbes siis, kui 50 uut passi müüki panime. VÕibla juhulik.
Aga seda on meil vaja, et passe luua ostjatele.

**Comment by LiisKasper** [comment]
Mihkel tegi katki ja Mihkel tegi korda.
Muutus ka transaction mudeli struktuur.
Shop / ost 2021 tabelis lisasin ka transaction ID sakile Ostetud_passide
