### ISSUE TITLE
Tee ümber industryProject credentials box pug

### ISSUE THREAD

**Issue by LiisKasper** [poff-bnff/web2021#399]
IndustryProjects [front](https://industry.poff.ee/project/bethlehem-light/).
Tee ümber pug, nii et ühe projekti credentials box kuvaks sarnaselt ühe filmi credentials box'iga.
Hetkel:
![Screenshot from 2021-11-08 09-33-29](https://user-images.githubusercontent.com/68702810/140701701-cacfaf3a-d233-4c06-bf38-e78286944bda.png)
 
Vaja oleks üks roll ja komadega eraldatud nimed järgi.
Rollide järjestus samasse järjekorda nagu filmide juures on.
nt:
![Screenshot from 2021-11-08 09-34-13](https://user-images.githubusercontent.com/68702810/140702005-10d3478d-35e4-4273-899d-d7b56efb8883.png)

**Comment by LiisKasper** [comment]
Mihkel kirjutas juurde fetch_industry_project_from_yaml koodi roles_in_project, mis tagastab data industryProject credentials box pug jaoks sobival kuju.
Alles jäi ka eelmine versioon. pole kindel milline pug seda võib veel kasutada.

**Comment by LiisKasper** [comment]
Soovitud olukord tekitatud, inimesed kuvavad rolli nimetuse järel komadega eraldatud listis.
Rollid järjekord pugis määratud.
![Screenshot from 2021-11-08 16-12-31](https://user-images.githubusercontent.com/68702810/140757083-26649f88-a82e-4030-8549-9694323ce0b6.png)

Võiks saada paremini, rollidel on Strapis olemas order, kui yaml, credentials lõikes, järjestada selle orderi alusel saaks pugis need lihtsalt läbi joosta ja saaks palju selgem

- [ ]  fetch'i ilusam yaml

**Comment by LiisKasper** [comment]
Harus industryProject_credentials_box_pug#339 on seis:
fetcher teeb yamli, mis vastab pugi credentials box vajadusele rolePerson ja RoleCompany piires.
yamlis on rollid koos inimsete ja rollinimedega järjestatud vastavalt Strapis olevale RoleAtFilm objektis määratud orderile.
Pug jookseb lihtsalt yamli läbi ja täidab koha, ei pea eraldi pugis rollide järjestust määrama. Samuti tuleb label mitte labelGroups alt vaid rolli juures määratud vastava keele väljalt. 

Näide, pilt ehitatud harus:
![Screenshot from 2021-11-09 14-31-05](https://user-images.githubusercontent.com/68702810/140924797-6437211d-1d75-4e15-bcaa-69d1ccf51ba3.png)
St kodulehe välimuses midagi ei muutunud.

Testimine: Labelid ei vasta labelGroups film all määratud nimetustele. nt Production vs Production Company
Enne muutimist, tuleb meenutada/uurida kes kasutavad keele väljades olevaid olemasolevaid väärtusi. Nt tablid ... 
Kõik RolesAtFilm rollid pole tõlgitud. (Strapis tuleb andemed koda teha). 

Tegele teemaga edasi, kui POFF on läbi!
ÄRA PANE ISSUET KINNI

**Comment by jaanleppik** [comment]
tegin selles branchis local buildi ja sain sellise tulemuse, et alates directorist credentials on topelt

![Screenshot 2021-12-13 at 12 38 17](https://user-images.githubusercontent.com/60266520/145802664-bc9ccf9a-7ce0-4fcb-9859-1bc4dabcf546.png)

**Comment by jaanleppik** [comment]
aga kas saan õigesti aru, et credentials täitmine toimub nagu filmilgi: 
* PUG määrab rollide järjekorra ja 
* Strapi order väli role_personi ja role_org juures määrab persooni ja org järjekorra rollis?

**Comment by LiisKasper** [comment]
Korduse tingis vahepeal kaduma läinud sõna algus. 
Rollide järjekorra määrab Strapis rolli juures kirjas olev order, kui seda pole, lisatakse roll kõike lõppu. Samuti ei kasutata rollide nimetamisel labeleid vaid rolli juures kirjas olev väärtusi. Igas keeles siis vastav.
Roll on kirjeldatud [RolesAtFilm](https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::role-at-film.role-at-film?page=1&pageSize=10&_sort=roleNamePrivate:ASC)
Hetkel inimese järjekorda antud rollis ei loeta. Tulevad järjest.

**Comment by LiisKasper** [comment]
Lisasin ka rolli sisese inimeste järjestuse koodi aga ei oska seda kenasti kuvama saada. Pug teadlikumad vast aitavad. 
Sama kood on vaja ka lisada siis RoleCompany juurde (hetkel kauvab [Object ]
![Screenshot from 2021-12-14 11-07-11](https://user-images.githubusercontent.com/68702810/145967827-fde078dd-4ea0-4896-9e86-4ffa2c97ec16.png)

![Screenshot from 2021-12-14 11-07-24](https://user-images.githubusercontent.com/68702810/145967857-d4403aea-fb08-476f-850f-bcf473d5e6d2.png)

**Comment by mpennaste** [comment]
Peaks nüüd kuvama ([](https://github.com/poff-bnff/web2021/commit/d81db4561bce6b5e7eb372818c19ea1d8b14eb15))
![image](https://user-images.githubusercontent.com/68708892/145997008-30620db7-a6f7-4260-9146-21c05a9e64ab.png)

**Comment by LiisKasper** [comment]
Aitäh!
See tähendab, et nüüd peaks harus olema olukord, kus IndustryProject cred kast on täidetud nii:
Rollide järjekorra määrab Strapis rolli juures kirjas olev order, kui seda pole, lisatakse roll kõike lõppu. Samuti ei kasutata rollide nimetamisel labeleid vaid rolli juures kirjas olev väärtusi. Igas keeles siis vastav.
Inimeste järjekord rollis on vastavalt Strapis määratud orderile (teamCredentials.rolePerson(Company) all oleva order järgi).

**Comment by LiisKasper** [comment]
Tegin uuesti korda ka selle haru.
Eelmine kommentaar annab ülevaate atud haru seisust.
Tõmban selle main harule peale.
Sellega teema lõpetatud.
