### ISSUE TITLE
Tabelist info saatmisel anna kaasa kasutaja

### ISSUE THREAD

**Issue by LiisKasper** [poff-bnff/web2021#408]
Hetkel on olukord: (jutt updated_by väljast Strapis ja selle täitmisest arusaamatutel põhjustel, öösel)
Martin Pennaste  10:44 AM
_"Nii on jah, läheb kirja selle nimi kes viimasena muutis ja kui seda pole, siis Google Sheets (id 48) ja ei tea kuidas seda lahendada hetkel. Sest Strapis muutes muutub ka updated_by, aga kui väljast tuleb, siis ei tea keegi kes lisas või muutis."_

Kõigepealt on meil vaja salvestada info, kes mingit rida(objekti) viimati muutis ja siis info, kes andmed üles laadis.
Strapis saab kokkuleppe alusel ära täita updated_by, ühe v teise väärtusega ja ilmselt tuleb täpsema info salvestamiseks tekitada erialdi komponent v collektion vms 
Kui hakkame ühendama kasutaja e-post ja meil vaja id, siis kasutajad peavad strapis olema sama e-postiga, millega teevad muudatusi tabelites.
Kuidas infot vastu võtta, kas e-posti ja id ühendmine teha tabli v Strapi poolel.

**Comment by LiisKasper** [comment]
Kas Strapis tahame muutjaks märkida tabelist info edasi/Strapisse laadinud inimese v objektiga viimati tegutsenud inimese. 
(nt mina muudan filmi sisu, aga filmi kirjutab Strapisse Jaan. Kumba nimi muutjana kirja läheb, Liis v Jaan?)

**Comment by mpennaste** [comment]
Kui näiteks keegi Toivo on kunagi Strapis lisanud filmi, siis üks (nt Liis) muudab tabelis selle filmi credentialsi, teine (nt Martin) synopsise jne, aga kolmas, nt Jaan, vajutab seda nuppu vms, et film reaalselt Strapisse läheks, siis sel juhul peaks kirja minema tema, sest tema vastutab lõplikult selle eest mis Strapisse läheb ja eelnevalt ka muu info kontrollimise eest. Seega antud näitel mina arvan, et Jaan peaks kajastuma Strapis (eelneva Toivo asemel siis).

**Comment by LiisKasper** [comment]
Tabel saadab nüüd kaasa ka kasutaja, kes filmi tabelist Strapisse saadab. Kuna Strapi admin(front) kasutajaid eraldi nt graphql päringuga küsida ei saa, siis kirjutasin kasutaja ja vastava id mappingu koodi (need kasutajad, kellega oli RAW tabelit jagatud).
Test filmina saatsin tabelist [Ride the Wave](https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::film.film/2661) filmi, id 2661
Selgub, et created_by, updated_by jne välju ei saa täita läbi api, ainult admin paneelis. 
**Küsimus**. Kas me tahame seda infot salvestada, lahendus oleks enda väljade loomine. Leidasin ka sellelaadse issue [SIIN](https://github.com/strapi/strapi/issues/8216)
Ühtlesi saadab tabel nüüd treileri info Strapisse. Siin kehtib tabeli ülemvõim. Kui Strapis on juba midagi kirjas siis tabeli info kirjutab selle üle.

**Comment by mpennaste** [comment]
Ma arvan selle info valguses, et siis pigem äkki juba salvestada ja hoida kusagil tabelis logina infot selle kohta mis hetkel ja kes mida sealt Strapile saatis?
Hakata igale asjale vastavaid välju juurde kirjutama ei kõla eriti cool.

**Comment by LiisKasper** [comment]
Strapisse tulevad film collection'i juurde väljad g_sheets_updated_at ja g_sheets_updated_by, mille sisu kirjutatakse üle vastavalt tabelist tulnud info aja ja kasutaja e-postiga.
Kui created_by on tühi siis on objekt loodud tabelist tulnud infoga. **Ei tekita** eraldi välju g_sheets_created_at ja g_sheets_created_by.

**Comment by LiisKasper** [comment]
Tabel täidab filmi objekti juures välju film.g_sheets_updated_at ja film.g_sheets_updated_by
Näide film [id 2661](https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::film.film/2661)
