### ISSUE TITLE
seansside kaardi juurde ka timestamp

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#413]
[seansiotsingu lehel](https://poff.ee/otsi_seanssi/) on tarvis iga kaardi juurde renderdada ka tema timestamp:

```html
<a class="card_film" id="2381" href="/film/eesti-ja-venemaa-lastestuudiote-animatsioon" ts="1636723429924">
  <div class="container_frame_16_9">
   ...
```
[How do you get a timestamp in JavaScript?](https://stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript)
`let timestap = +new Date`

Seda on tarvis selleks, et browseri extension saaks jooksvalt eemaldada DOMist elemente, mis on minevikus

**Comment by mitselek** [comment]
Kui nyyd 
- brauserile installida extension (ala custom javascript 2);
- siis navigeerida soovitud lehele;
- ja installida j2rgnev skript
  ```html
  document.getElementsByTagName('header')[0].remove()
  document.getElementsByTagName('footer')[0].remove()
  document.getElementById('filters').remove()

  let cards = document.getElementsByClassName('card_film')

  let njau = new Date().getTime()
  for (card of cards) {
    if (card.getAttribute('ts') < njau) {
      document.getElementById(card.id).style.display = "none"
    }
  }
  ```

**Comment by jaanleppik** [comment]
lisaks oleks vaja modida iga kino seansside lehte, a'a
https://poff.ee/otsi_seanssi/?cinemas=Coca-Cola%20Plaza
nii, et peidaks ära päise ja filtrid
Kas see oleks u nii, et teeme otsi_seanssi pug'ist koopia, kus css'i abil või mingite inclu'dede välja jätmise abil kaotame ära päise, filtrid aj footeri?

**Comment by mitselek** [comment]
Eraldi kinode lehti võib ka toota `https://poff.ee/kino/coca_cola_plaza`, kuhu siis polegi renderdatud päiseid ja filtreid.

Kui ikka piirduda brauseri extensioniga, siis see skriptike toimib kogu `https://poff.ee/otsi_seanssi` ulatuses

**Comment by jaanleppik** [comment]
võidetavalt on meie leht ja kood nii raske, et seda lihtsama meidaplayeri peal sel viisil näidata ei saa
filtrite joonistamine võtab aega, ja siis nende peitmine, ja ei ole multithreadi tuge ja lööb yhe prose tuuma lakke ja vaataja näeb tykk aega lehte, kus on header ja footer ja filtrid ...

**Comment by mitselek** [comment]
Tuleb siis teha korralikult, et renderdame igale kinole oma lehe
