### ISSUE TITLE
Eventivaliga sisse logimiste logi

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#449]
Kas meil on Eventivaliga autentimiste / sisse logimiste kohta logi? 
Keiss näiteks selline, et vaja praegu teada ühe inimese kohta, kas ta on Industry lehele sisse loginud tänavuse ürituse ajal?

**Comment by mpennaste** [comment]
Vastatud toona slackis. Viimaseid logimisi saab vaadata Strapis user'i alt.
