### ISSUE TITLE
Tabelist API kaudu Komponendi sisse kirjutamine ja update'mine

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#464]
kas ja kuidas saame komponendi sisse kirjutada ka siis, kui komponendis on juba info sees?
Näiteks Filmi media komponent:
- Stills on sees, lisatud otse Strapis
- Tabelist on vaja lisada treiler

Kas saab selliste sammudega kirjutada, et 
- loeme komponendi sisu, seal sees oleva info 'võtame mällu või kirjutame kuhugi maha', 
- võrdleme komponendis juba olevat ja lisatavat infot
-- kui on vastuolu, siis kehtiub tabelis olev info
- paneme kokku kogu komponendi uue info: selle, mis oli enne komponendid sees kui ka uue, lisatava info
- kirjutame komponendi sisu uuesti summaarse infoga yle

* Kas saame komponendi sees olevat infot selle protseduuri käigus lugeda?
* Kas pildid lisavad keerukust? Kas pildi infot saame komponendi seest lugeda nagu näiteks teksitlist infot?

**Comment by jaanleppik** [comment]
Teoreetilisi küsimusi veel:
Komponendi 'liitinfo' uuendamine ka tabelis, peale Strapis uuendamist?
mis sammudedt see koosneks?
mis otsused tuleb selle käigus teha?
kuidas on komponendis kirjeldatud pildifailid? kas neid saame kah tabelisse kirjutada / infot dubleerida?

**Comment by LiisKasper** [comment]
**Stills on sees, lisatud otse Strapis** - graphql võimaldab meil küsida komponendi sees oleva pildi andmeid nt id.
**Tabelist on vaja lisada treiler** - saame läbi tabeli lisada nt traileri urli ja samal ajal uuesti üle kirjutada pildi id, mille olime enne küsinud

**loeme komponendi sisu, seal sees oleva info 'võtame mällu või kirjutame kuhugi maha',** - jah saame seda teha, StrapiMirror pm täiab juba seda rolli.
**võrdleme komponendis juba olevat ja lisatavat infot 
-- kui on vastuolu, siis kehtiub tabelis olev info
paneme kokku kogu komponendi uue info: selle, mis oli enne komponendid sees kui ka uue, lisatava info
kirjutame komponendi sisu uuesti summaarse infoga yle** - mina sisulist teksti võrdlust teha ei oska vb @mitselek. Aga tunub väga mahukas ja ajakulukas tegevus. Ma ei julge uskuda, et sheets sellega hakkama saab. 

**Komponendi 'liitinfo' uuendamine ka tabelis, peale Strapis uuendamist?** jah, saame lugeda info Strapist ja siis kirjutada selle tabelisse. Mina seni kirjeldatud juhul küsiks esmalt uue info Strapist, enne kui toimetaja hakkab midagi tabelis täitma. Ja peale toimetaja tegevusi kirjutaks selle info Strapisse tagasi. Aga see tähendab ühe filmiga eraldi tegelemist. Pm võiks juba Strapis infot sisestada, mitte kirjutada läbi tabeli.

**Comment by LiisKasper** [comment]
Vestluse tulemusena:
andmemudel muuta kus komponent ei sisalda enam treilerit ja QaClip

**Comment by mitselek** [comment]
### sammud komponendi lammutamiseks

1. lisaväljad andmemudelisse;
2. sql skript andmeliiasuse loomiseks;
3. fetcherid lisavälju lugema;
4. komponendid kustutada.

**Comment by jaanleppik** [comment]
Cassette all on samuti Media komponent

**Comment by mitselek** [comment]
https://stackoverflow.com/questions/70606020/how-to-add-custom-properties-to-media-field

**Comment by LiisKasper** [comment]
Lisan live Strapis filmi alla otse trailer komponendi, et andmebaasis päringuid kirjutama hakata.

**Comment by jaanleppik** [comment]
DEVis tõstsin filmi ja kasseti meedia MEDIA komponendist välja

**Comment by LiisKasper** [comment]
Päring andmebaasis, liigutamaks info meedia komponendi seest kõrgemale tasandile.
Olemas on film.trailers ja film.QaClips
Antud päring ei toimi stillide ja posteritega, hetkel ei saa veel aru, kus hoitakse piltide seoseid objektiga.
``` sql
-- INSERT INTO public.upload_file_morph ("upload_file_id", "related_id", "related_type", "field", "order")

SELECT 
	  mor.upload_file_id
	, film.id
	, 'films'
	, mor.field
	, mor.order
FROM public.films as film
left join public.upload_file_morph as mor
	on mor.related_id = film.id
where mor.related_type = 'components_media_film_medias'

ORDER BY film.id DESC 
```

**Comment by LiisKasper** [comment]
Lisaks soovis Jaan StrapiMirrorisse filmi stillide ja posterite kohta infot. Hetkel saab antud graphql päringi errori, kuna kuskile on lisatud pilt, mis hiljem kustutatud. 
Teha andmebaasi päring, mis kustutab filmi stillidest ja posteritest katkised pildid. [PÄRING ](https://github.com/poff-bnff/web2021/issues/295#issuecomment-1011870529)

**Comment by LiisKasper** [comment]
Stillide ja posterite info [StrapiMirror, Films](https://docs.google.com/spreadsheets/d/1_uqz7-HxwPHvG3k-amwkcroGQNgRKRQGkYGP2AZflm0/edit#gid=841503595) lehe päringus ja väärtused tulpades G ja H.
