### ISSUE TITLE
URLi suunamine / 

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#505]
Oleks vaja teha taas 1 suunamine ja paneks selle protsessi ka wikina kirja:

hoff.ee/votemo

ja suunata see ühele kindlale artiklile

Wiki page tegin:
https://github.com/poff-bnff/web2021/wiki/URL'i-suunamine

**Comment by mpennaste** [comment]
Ma lahendaks selle aliasena nagu seni tehtud. St artikli alias ehk lisaks artikli enda aadressile (path) veel aadress(id) kus kuvatakse täpset samaväärset koopiat.
Näide: https://github.com/poff-bnff/web2021/blob/d4b9d8097a5ac7360a130225397aced7814e4745/ssg/helpers/fetch_article_type_from_yaml.js#L193
St kui slug on "lemmikfilm" siis lisaks artikli pathile on aliasteks nt (poff.ee)/lemmikfilm ja (poff.ee)/publikulemmik

Antud juhul siis midagi sellist: https://github.com/poff-bnff/web2021/blob/2b93ae8fe238ce3f3b7ef044f870fd88deaa0198/ssg/helpers/fetch_article_type_from_yaml.js#L204

Seal siis kõik sarnane, lisaks vaid see, et kontrollin ka domeeni (et rakenduks vaid hoff.ee puhul).
PS! Testisin ja avastasin järsku, et see keelt ei arvesta (üritab kõiki keeli aadressile /votemo kirjutada) tuleb ise kaasa anda ja lisasin selle osa juurde.

https://build.hoff.ee/votemo/

**Comment by jaanleppik** [comment]
Proovin siis muuta ja selle käigus aru saada, kuidas see toimib.
