### ISSUE TITLE
kolmetasandiline menu

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#512]
@LiisKasper palun mõtle, kuidas me saaksime Strapis teha kolmetasandilise menu. 
Siis teeme sel teemal arutelu.

**Comment by LiisKasper** [comment]
Saame teha seda nii nagu hetkel on Strapis on tehtud, komponent, millel on korratav alamkomponent ja sellel omakorda korratav alamkomponent. Toimetaja saab ise menüü kokku laduda, toimetajale kergemini arusaadav.
Saame ka abstraktsemalt. nt luua collectoni menu, mille all kirjas tema navigation vms (parent menu ja child menu) ja category, mille alla siis saab vastavad artiklid (poffis, domeeni põhised), filmid jne linkida. Nii nagu [arh liidus](https://admin.arhliit.ee/admin/plugins/content-type-builder/content-types/application::menu.menu) tegeime.

**Comment by jaanleppik** [comment]
hea ilus näide kolmetasandilisest menüüst: https://www.rapha.cc/eu/en/

**Comment by LiisKasper** [comment]
Komponentidega menu tegemine osutus keerulisemaks kui arvasin. Strapi ei lase nii sügavaks komponente ajada. Sellest sain mööda, lisasin backis otse koodi ja toimib. Näide [BrunoMenu](https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::bruno-menu.bruno-menu/13). 
Järgmine probleem on selles, et meie kooodid b-fetch jne ei rikasta nii sügavat infot. Strapi ei tagasta seda. Ehk meil on collection mille sees on component mille sees on component, mis viitab ka võimalusena artikli collectionile, artikli juurest type enam Strapi ei tagasta. 
@mpennaste milleks on oluline artikli tüüp frondis? viite urli ehitamiseks?
@jaanleppik kas teeme menu mudeli ja loogika ümber või läheme sellega edasi, teeme lisapäringud jne

**Comment by mpennaste** [comment]
Artikli tüüp on jah oluline selleks, et ehitada õige (just antud tüübile kohase) template baasil ja ka URLi osas, ala, et tavaline artikkel ikkagi ilmuks artikli templates määratud kujundusega ja artikli-URLiga (https://poff.ee/**uudis**/tartuffi-avab-kauaoodatud-eesti-film/) ja näiteks toetajalugu vastavalt toetajaloo kujundusega ja toetajaloo-URLiga (https://poff.ee/**toetajalugu**/lux-express/)

**Comment by jaanleppik** [comment]
fetcheri pole veel õigusi uut menu collectionit lugeda

**Comment by mpennaste** [comment]
Esimene ja teine punkt on reaalsuses tehtud, st fetcher YAMLide tegemiseks olemas, aga pole lisanud seda build scriptidesse ja mujale ega testinud seda, et see teiste lehtede buildil erroreid ei viskaks (saanud aru, et see kolmetasandiline on esialgu ainult Industry teema). 
Kolmanda punkti osas, sain aru, teeb keegi HTMLi ja CSSi ära. Seejärel kui see olemas saab kolmanda ja neljanda punktiga edasi minna, st genereeritava YAMLi pealt ka siis info võtta.

**Comment by jaanleppik** [comment]
ma tahaks, et nad teeks kohe meie YAML'i ja PUGiga tööd, aga arutame kell 2

**Comment by jaanleppik** [comment]
miline see 3t menu infoga YAML on?

**Comment by jaanleppik** [comment]
Kumu 3tasandiline menu on tehtud ja datamodel uuendatud ja Live pandud

**Comment by mpennaste** [comment]
Fetcher mis peaks menu2 osas tegema ära kõik mis praeguses menus teostatakse PUG tasandil.
St sorteerib, filtreerib, genereerib linke, teeb vaid vajaliku infoga YAMLi:
ssg\helpers\fetch_menu2_from_yaml.js

Menu2 kaust:
ssg\source\menu2

Seal siis kaasatakse vastavad keelepõhised YAMLid ja domeenipõhine template.

Hetkel ehitatakse vaid Industry ja KUMU puhul ning asub aadressil lehe.aadress/menu2

Ise testisin ning arvan, et valmis edasiseks testimiseks ning läks live.

Target build veel tegemata, aga peaks tegema ja ei tohiks ülemäära keeruline menu puhul vast olla.

**Comment by jaanleppik** [comment]
Testin LIVEs:
https://build.kumu.poff.ee/menu2/

customUrlid ei toimi - need luuakse läbi /menu2/ - https://build.kumu.poff.ee/menu2/otsi_filmi

**Comment by mpennaste** [comment]
Tundub, et sain parandatud. Lisaks avastasin veel probleemi keelte osas, st customurl oli ilma keeleta a'la `https://build.kumu.poff.ee/programmes` vs `https://build.kumu.poff.ee/en/programmes` (mis peaks olema õige). Selle fixisin ka.
Võib testida, sulgen issue ja kui midagi veel ilmneb, siis saab taasavada.
