### ISSUE TITLE
StrapiMirrori täiendused

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#516]
Palun EventType collectioni infot StrapiMirrorisse
nimed kolmes keeles piisab, kirjeldusi pole vaja

**Comment by LiisKasper** [comment]
Olemas sakil [EventTypes ](https://docs.google.com/spreadsheets/d/1_uqz7-HxwPHvG3k-amwkcroGQNgRKRQGkYGP2AZflm0/edit#gid=973081984)
