### ISSUE TITLE
Front_Page_Courses muutus Course -> CourseEvent

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#577]
Teen ümber Front Page Courses mooduli nii, et seal oleks relatsioon mitte enam Course'le, vaid CourseEventile. 

Siis palun uuendada datamodelit ja ka fetcherit.

**Comment by LiisKasper** [comment]
Datamodeli update olemas

**Comment by jaanleppik** [comment]
Palun fetcher kah nii ümber teha, et see võtaks course asemel courseevents objekte:
fetch_frontpagecourse_block_from_Yaml.js

**Comment by LiisKasper** [comment]
Lisasin ise filmikooli frontPageCourses alla course_events objektid, vt need üle.
Fetcher tegeles ka stillidega.
Course all on olnud stillid mida courseEvent all pole, kas nii jääb?
Stillide asemel images

**Comment by jaanleppik** [comment]
Jep, stillide asemel images on hea, portrait e poster on kah mõlemal olemas. Võtsin

**Comment by LiisKasper** [comment]
uuendasin frontpagecourses fetchi ja .._filmikool ja .._discamp pugi.
Pull request https://github.com/poff-bnff/web2021/pull/580
mainis ja serveris

**Comment by jaanleppik** [comment]
Aitäh! Testin ja ehitan

**Comment by LiisKasper** [comment]
Tundub, et teema lõpetatud, sulgen
