### ISSUE TITLE
Industry project tabelist Strapisse

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#586]
- [x] - Jaan loob tabeli Projekti info struktuuriga - multiselect tabeli koopi alusel
- Liis teeb info strapisse liigutamise osa

**Comment by LiisKasper** [comment]
[Max info tabel siin.](https://docs.google.com/spreadsheets/d/1SXJOqPXFDgdRwB8MwTXZ2ERnXfiym_y1i_agRzBMhto/edit#gid=0)

Kuidas rolle täitma hakatakse? tulbad AJ:AN
Olemasolevad inimesed multiselectist?
Komadega inimesed, nii nagu filmi tabelis, pean enne inimese looma ja siis ta projekti ja rolliga siduma?

**Comment by jaanleppik** [comment]
Kui teha nagu filmide tabelis. siis ei peaks inimest enne looma - kui teha täpselt nagu filmdie tabelis. Et kõigepealt lood inimesed ja siis saad neid inimesi Filmide credentialisse lisada.
Aga võib ka teisiti. Need inimesed on vähemalt pooles mahus enama infoga, kui filmide credentiali inimesed. E neil on ka bio näiteks jms. 
Nii et kindel on see, et jah, peavad olema persoonid, mis on Strapis olemas. Aga kuidas neid projekti alla lisada - mis sa arvad?
Kuidas on sul lihtsam teha või kuidas sa tahaskid teha?
Mul pole raudbetoon soovi lisamise viisi kohta.

**Comment by LiisKasper** [comment]
Tabelis oleks vähem tööd, kui inimene on enne juba olemas. Ei peaks mitut päringut tegema. Ja kui sa ütled, et enamasti persoonidel ka rohkem infot kui nimi, siis see ka hea põhjendus miks enne teha valmis Persion max info tabelis persoonid, lisada need Strapisse ja siis alles lisada Projectide max info tabelis projektid.

**Comment by jaanleppik** [comment]
OK, teeme siis niipidi. Et saab valida ainult olemasolevaid persoone.

**Comment by LiisKasper** [comment]
Sain lõpuks andmete saatmise tööle. 
Hetkel on kolme objekti andmete saatmise loogika, ühes [tabelis](https://docs.google.com/spreadsheets/d/1p_iN1Bdg9IO8lne8buc51DOUjm7JkTurFkmGQamYeJk/edit#gid=1658017520). Kui see tundub ebamõistlik või mitte kasutaja sõbralik, siis teeme ümber.
Eeldused: 
toimetajate [tabelist](https://docs.google.com/spreadsheets/d/1SXJOqPXFDgdRwB8MwTXZ2ERnXfiym_y1i_agRzBMhto/edit#gid=0) tuleb kõik korratav info läbi multiselecti, 
kogu projekti juures kasutatav info juba Strapis olemas.
Objekti Strapi id tuleb toimetajate tabelist, tulp A. Kui seda pole, luuakse Strapis uus objekt.
Selleks, et andmeid saata tuleb teha linnuke, toimetajate tabelis, tulpa G "Kodulehele".
Olemas peab olema Title EN, tulp H (toimetaja tabel)

Küsimus tekib slugiga, 
Ilma slugita Strapi päringut ära ei tee, hetkel lisasin selle raw tabeli juurde. 
Slug tehakse Title EN pealt. Aga see on koht, kus toimetaja tahaks vb ise määrata slugi (eriti korduva pealkirja puhul).
Kas lisada slugi väli toimetajate tabelisse, siis tuleb jälgida, et toimetaja teeks ikka slugi reeglite järgi. Või lisada tabelisse toimetajale automaatselt genereeritud slug, mida tal on võimalus muuta?

**Comment by jaanleppik** [comment]
vastan slug'i kohta: pigem automaatne, kui tahta muuta, siis saab seda teha Strapis. 
Mul on üks Google tabeli slugify laadne asi tehtud, filmide info tabelis, FILMIDE_INFO sgeedil BK tulbas, seda saaks kasutada.

**Comment by LiisKasper** [comment]
Selge, slug läheb automaatselt title en järgi ja muudatused Strapis. Slug nagu ikka UID

**Comment by LiisKasper** [comment]
Minu poolt võib teema lõpetatuks lugeda, kas keegi tahab veel midagi lisada?
