### ISSUE TITLE
Person Form kaudu näitlejate profiilide yle toomine

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#587]
https://filmestonia.eu/index.php/estonian-female-actors/
https://filmestonia.eu/index.php/estonian-male-actors/

meie industry /add_pro vormi kaudu peaks sealsed profiilid meile üle tooma
Ja kõik kommentaarid kirja panema, mis selle käigus tühele paned

**Comment by LiisKasper** [comment]
[10:56 AM](https://pff-dev.slack.com/archives/D0183QNECD7/p1665042965768789)
Jaan Leppik
 Hommikust!
jagasin sinuga näitlejate piltide kataloogi
need on praegu Film Estonia lehel olevzte näitlejate pildid
mis on meile sobivamaks tehtud (WebP -> jpg)
me peaksime kõik need sealsed profiilid omale üle kandma
https://filmestonia.eu/index.php/estonian-female-actors/
https://filmestonia.eu/index.php/estonian-male-actors/
meie vormi kaudu peaks neid üle kandma
mõned on mul juba tehtud
kohe annan aadressi, kus need praegu on
https://industry.poff.ee/persons-search/
mõni neis pole täies mahus yle toodud
Ja pane kirja, issue alla,
kõik kommentaarid
näiteks:
awarde meie infos veel pole
seal forode kataloogis on see peamine profiilippilt märgistatud sq_prefiksiga
ja kui on fotograafi nimi teada, siis on see pildi nimes kirjas (enamasti pole)
(fotograafi nimi ja foto aasta kah ei liigu veel caption väljale)
ja kui näed midagi, mida tahad fiksida - siis anna minna :slightly_smiling_face:

**Comment by jaanleppik** [comment]
Sest et me peame vormi kah arendama ja siluma ja parandama

**Comment by jaanleppik** [comment]
ja läbi tabeli lisamiseks meil filmograafia ja educationi osa ei ole tehtud, ja enamus profiilist on just see osa

PS! Kõigil otsi ise juurde
1. profiil efis.ee lehel
2. profiil imdb.com lehel

**Comment by LiisKasper** [comment]
vahemärkus, Strapis otsides, firstNameLastName contains Urge ei anna vastet.
Ja meil kedagi Tituss Burgess 4 korda.
![Screenshot from 2022-10-06 13-04-45](https://user-images.githubusercontent.com/68702810/194286328-71429d3d-fc3b-4f76-ab06-d0cdc7b4f039.png)

**Comment by LiisKasper** [comment]
sobivat juukse värvi pole, lisasin strapis
kogu info salvestatakse ühes keeles nt skills

**Comment by LiisKasper** [comment]
kui Strapis rohkem toimetamist, siis salvestmine võtab väga pikalt, korra nt 5 min. Selle ajaga hakkab kasutaja küll viga otsima. Ühe persooni andmed ei jõudnudki kohale, filmographies kirjutas ära ja persooni ei loonud (ühendusi ka mitte). Ette jäi poolikult täidetud persooni profiil, ilma hariduse ja tööta. seda salvestada enam ei lubanud, st nuppu siad klõpsata aga midagi ei juhtunud. reload tegi lahtrid tühjaks ja vaja uuesti andmed sisestada

**Comment by LiisKasper** [comment]
Inimestel vahetuvad perekonnanimed.
ja siis kui sisselogimse aeg peaks läbi saama sellel ajal kui andmeid täidad, siis saatmine ei õnnestu ja kogu info läheb kaduma

**Comment by LiisKasper** [comment]
Filmestonia lehelt soovitud näitlejad käsitsi tõstetud Poffi andmebaasi. andmete sisulise õigsuse eest ei vastuta.
