### ISSUE TITLE
Persooni biography struktuur komponendist lapikuks

### ISSUE THREAD

**Issue by LiisKasper** [poff-bnff/web2021#588]
Mitme objekti struktuur on muutunud lapikuks.
Nt Persooni biography

teema algatus slackis:
[11:10 AM](https://pff-dev.slack.com/archives/D0183QNECD7/p1665130235023509)
Jaan Leppik
praegu ainult nimi ja bio ja filmograafia (tekstiline)
ja nyyd on seis, et varem kirjutasime biographyd komponenti
aga nyyd lapikusse
kas nyyd on 2 varianti filmi juurde selle info saamiseks: kas kirjutada ümber fetcher või kirjutada bio korraga lapikkusse ja komponenti?
või siis kolmas: tõsta baasis kõik senised biod ümber lapikusse ja siis teha fetcher lapiku peale ümber?

[11:34 AM](https://pff-dev.slack.com/archives/G017XBQ5UJY/p1665131651501649)
Jaan Leppik
lahendamist vaja olukord, et personi all on bio nii komponendis kui lapikuna ja varasemad biod on komponendis, uuemad lapikuna.
mulle tundub, et kõige korrektsem oleks
tõsta baasis info komponendist lapikkuse
teha ümber fetcher, mis personite infot võtab - sh filmi lehe ehitamise fetcher, personi lehe ehitamise fetcher, jm

Selleks on vaja
- [x] andmebaasi päring, mis tõstab info ümber
- [ ] kontrollida scriptides, tabelites jne. Et info kirjutakse lapikusse struktuuri
- [ ] vajadusel teha muudatused, et andmed liiguks õigesse kohta 
- [ ] kontrollida andmeid kasutavad scriptid
- [ ] teha muudatused andmeid kasutatavates scriptides
- [ ] ....
- [ ] kustutada komponent

**Comment by LiisKasper** [comment]
> * [x]  andmebaasi päring, mis tõstab info ümber
> *

Andmebaasis bio väljad lapikus struktuuris (bio_et, bio_en ja bio_ru)
Päring näide ru ( x3, vastavalt keelele)
``` sql
update public.people as people
set bio_ru = compl.ru

FROM public.components_translated_translated_longs as compl
left join public.people_components as plc
	on compl.id = plc.component_id
	
where people.id = plc.person_id
and plc.id is not null
and plc.field = 'biography'
and compl.ru is not null
and people.bio_ru is NULL

returning *
```

**Comment by LiisKasper** [comment]
> * [ ]  kontrollida scriptides, tabelites jne. Et info kirjutakse lapikusse struktuuri
> * [ ]  vajadusel teha muudatused, et andmed liiguks õigesse kohta

Persoone kijrutame Strapisee hetkel kahest tabelist.
Filimide tabelist kirjutame persoonile ainult firstNameLastName, 
Persoonide max info tabelist juba kirjutame lapikult (bio_et, _en ja _ru)

Minule hetkel rohkem tabelid meelde ei tule. Täienda, kui sinu teadmised on teised!

**Comment by LiisKasper** [comment]
> * [ ]  kontrollida andmeid kasutavad scriptid
> * [ ]  teha muudatused andmeid kasutatavates scriptides

Minu teada on meie fetcerid nii targad, et neid pole vaja ümber teha, info on yamlites juba olemas.

**Comment by LiisKasper** [comment]
> [ ] ....

Kui keegi kellegi rohkem ideid selle teemaga pole, siis kustutan lähipäevil komponendi relatsiooni ja sulen teema

**Comment by jaanleppik** [comment]
paun teeme ka YAMLite kontrolli 
- kas lapiku bio onfo on YANL'is olemas
- mis muutujanimega on lapiku bio info YAMLis
