### ISSUE TITLE
 Industry events search (courseevents)

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#601]
Filtrite täiendus:

https://industry.poff.ee/industry-events-search/
ssg: industry_courseevents_search

Industry ajaks palun lisame filtreid ja mõne kaotame / peidame:

industry_categories - olemas, OK
dates - olemas, jaan teeb ika päeva kohta oma staatilise kasti, aga praegu las jääb nagu on
event_type - lisame
event_mode - lisame
is_live_event - lisame
event_access - lisame

**Comment by mpennaste** [comment]
Lisatud:
event_type
event_mode
is_live_event (true === Yes, false === No)
event_access

**Comment by mpennaste** [comment]
See vist ka OK, sulgen, kui ei ole, saab uuesti avada
