### ISSUE TITLE
Filmi / kasseti target build ehitab ilma rež infota lehe

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#620]
Target build ehitab ilma rež infota lehe, full build ehitab koos rež infoga lehe.

**Comment by mpennaste** [comment]
Vaatasin mõnda aega koodi, testisin, ka lives lõpuks... https://build.hoff.ee/film/mtlik/ ja https://build.poff.ee/film/mtlik/ mõlemal on olemas pärast target buildi. Viga ei tuvastanud.

**Comment by jaanleppik** [comment]
Seda on mitu korda juthunud. 
Laen tabeli kaudu filmi üles. -> Strapis on Rež olemas, lehele target buildiga ei ehita. -> Full build ehitab filmi rež'ga.

**Comment by jaanleppik** [comment]
Praegu just kordasin keissi:
Tabeli kaudu uus film
https://build.hoff.ee/film/kssarvikute-sda/
Strapis Rež olemas
Target build ehitas ilma rež'ta

**Comment by jaanleppik** [comment]
kustutan filmi praegu ära, sest see pole veel avaldamiseks valmis.

**Comment by mpennaste** [comment]
Võin eksida, aga esmaste järelduste osas siin tundub äkki peitubki asjaolu just uue persooni lisamises? St kui full buildi ei toimu, pole vast ka lisatud uut persooni keda sinna kassetile/filmile külge pookida?
Sest vaadates logisid, sattus minu test peale full buildi ja siis kõik nagu toimis ja ilmus režissööri blokk.

**Comment by jaanleppik** [comment]
Filmi tabelist laadimise loogika:
1. tabel filtreerib inimesed filmi andmetest välja, ja esimese sammuna laetakse inimesed tabelist Strapisse.
2. tabel saab Strapi Mirrorist inimestele Strapi ID juurde, nii et alles siis, kui inimestel ja prganisatsioonidel e objektidel millega filmil on relatsioonid, on Strapi ID olemas e nad on Strapisse loodud ja nende ID tabelile edastatud. 
3. siis saab tabel luua json objektid, nii et filmi info Strapisse laadimisel viitab juba inimestele ja organisatsioonidele nende Strapi ID kaudu

Praegu laadisin filmi, Hullumeelsuse lõugade vahel, mille kõik inimesed olid uued, e neid enne Strapis polnud. 
Laadisin inimesed strapisse, sain ennde ID'd tagasi, siis laadisin filmi Strapisse. Käivitus target build. 
Ehitas filmi lehe valmis, teised inimesed on credentialis olemas, aga rež mitte
https://build.hoff.ee/film/hullumeelsuse-lugade-vahel/

**Comment by mpennaste** [comment]
See vist ka OK, sulgen, kui ei ole, saab uuesti avada
