### ISSUE TITLE
Mixin / hero artikli video

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#621]
Palun vaata, mida teha, et Hero artikli video taas mängima saada. 
Näide, kuhu Vimeo video on lisatud:
https://admin.poff.ee/admin/plugins/content-manager/collectionType/application::bruno-article.bruno-article/35
https://build.oyafond.ee

**Comment by mpennaste** [comment]
Siin ma vaatasin ja uurisin-puurisin. Kas on võimalik, et Vimeol miski uues formaadis jagamis link nüüd?
Sest videoAp mixinis kasutatakse urli ja siis võetakse võrdusmärgi (=) järel olev videokood. Samas sellel artiklil lisatud Vimeo lingis võrdusmärki pole.
Kui on uues formaadis siis peaks mõtlema, et kas ka vana formaat peaks olema toetatud ja ka uus formaat tööle panna.

Lisaks on meil Vimeo jaoks ka heroVideo mixin mida tundub et kusagil ei kasutata ja mis samuti pole korrektne, aga sain ta nt tööle niiviisi:
![image](https://user-images.githubusercontent.com/68708892/222963281-4c2ea308-9fa7-4078-91d6-667bcc49fd46.png)

Küll aga üldse... mõlemal mixinil määratud Vimeole `width='560' height='315'` ehk siis tulemus jääb kehv nagu allpool näha
![image](https://user-images.githubusercontent.com/68708892/222963088-949e7419-1a00-4cad-8fcb-e35f0e03c183.png)

**Comment by jaanleppik** [comment]
Vaatan seda laiuse teemat, jah. 
Vimeo jah muudab seda videote URLide / slugide loogikat, olen ise kah sellega maadelnud, kuna seadistasin PÖFFi vimeot ja püüdsin sealt yldse videote avalikke linke kätte saada.

**Comment by jaanleppik** [comment]
mis branchis see kood on? kui teen livega buildi, siis ei näe videot.

**Comment by mpennaste** [comment]
Seda polnudki veel, panin siia lihtsalt näidised, sest mul tekkis liiga palju küsimusi. Muutsin bruno artikli pugi ja mainitet mixinit ning panin maini nüüd.

**Comment by mpennaste** [comment]
See vist ka sai korda, sulgen
