### ISSUE TITLE
Industry course-events / kalender / favourites

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#683]
https://industry.poff.ee/industry-events-search/

Ses vaates on igal sammul kalendrisse lisamise nupud. 
- need peaks lisaks ical faili allalaadimisele toimima ka add to favourites nuppudena, kui kasutaja on sisse loginud
- eventide uut listi peaks filtreerima favourites parameetri alusel

pug: `ssg\source\industry_courseevents_search\index.pug`

https://github.com/poff-bnff/oauth/commit/7c7ae785904bd397939af26327e17242974a44e4 Hundi vastav api:
```
### Switch my favorite course event
put {{hunt_url}}/api/my/courseevent HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

841

```

**Comment by mitselek** [comment]
sellised peaksid olema nupud
![image](https://github.com/poff-bnff/web2021/assets/873710/ecdd0775-a52b-4049-924d-96944c978fe8)

**Comment by mitselek** [comment]
enamvähem olemas - nuppude viimistlemisega ei jõua tegeleda
