### ISSUE TITLE
CG2: personite fetcheri täiendus

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#690]
Personite fetcher [fetch_person_from_yaml.js](https://github.com/poff-bnff/web2021/blob/main/ssg/helpers/fetch_person_from_yaml.js) filtreerib kõigist persoonidest välja:
- need, kellel on FE olemas:
  ``` js
  const activeEditions = DOMAIN_SPECIFICS.active_editions['industry.poff.ee']
  const personsWithEditions = STRAPIDATA_ALL_PERSONS.filter(p => p.festival_editions && p.festival_editions.length)
  ```
- ja kelle FE kuulub domain specificus kirjeldatute hulka:
  ``` js
  const activePersons = personsWithEditions
       .filter(p => {
           const feIds = (p.festival_editions || []).map(fe => fe.id) || []
           return feIds.some(id => activeEditions.includes(id))})
  ```

### Ülesanded
- [x] Lisada DOMAIN_SPECIFICS uue peatüki
  ``` yaml
  industry_person_in_editions:
      is_in_industry: [68]
      is_in_creative: [59]
  ```
- [x] Tuua persooni esimesse tasandisse kategooria tunnused
  ``` json
  {
    "is_in_industry": true,
    "is_in_creative": false,
  }
  ```
- [x] Luua iga kategooria kohta oma indeksi ja filtrite andmefailid:
  - `search_persons.${lang}.yaml` asemel `search_persons_${activeCategory}.${lang}.yaml`
  - `filters_persons.${lang}.yaml` asemel `filters_persons_${activeCategory}.${lang}.yaml`
    
- [x] Lisada "is_in_industry" filter ([WEB](https://industry.poff.ee/persons-search/) / [PUG](https://github.com/poff-bnff/web2021/blob/main/ssg/source/persons_search))
  data.yaml'ides ka viidata kategooriaspetsiifilistele andmefailidele
- [x] Kopipastada samasugune PUG ainult teise filtriga

**Comment by mitselek** [comment]
Personite fetcher [fetch_person_from_yaml.js](https://github.com/poff-bnff/web2021/blob/main/ssg/helpers/fetch_person_from_yaml.js) filtreerib kõigist persoonidest välja:
- need, kellel on FE olemas:
  ```
  const activeEditions = DOMAIN_SPECIFICS.active_editions['industry.poff.ee']
  const personsWithEditions = STRAPIDATA_ALL_PERSONS.filter(p => p.festival_editions && p.festival_editions.length)
  ```
- ja kelle FE kuulub domain specificus kirjeldatute hulka:
  ```
  const activePersons = personsWithEditions
       .filter(p => {
           const feIds = (p.festival_editions || []).map(fe => fe.id) || []
           return feIds.some(id => activeEditions.includes(id))})
  ```

### Ülesanded
- [ ] Lisame DOMAIN_SPECIFICS.active_editions['industry.poff.ee'] hulka ka CG editioni(d)

**Comment by mitselek** [comment]
Testida saab sedasi, et vaatab, kas [persons-search](https://industry.poff.ee/persons-search-cg/) ja [persons-search-cg](https://industry.poff.ee/persons-search/) toimivad
