### ISSUE TITLE
Eventival log in via Strapi

### ISSUE THREAD

**Issue by SiimS1** [poff-bnff/web2021#78]

**Comment by jaanleppik** [comment]
Mida me Eventivalist iga kasutaja kohta teada saame, kes end Eventivaliga auendib?
eesnimi?
perenimi?
pilt (mis kujul, st kas ruuduks kadreeritud või otiginaal?)?
Akre, mis tal hetkel küljes on?
Tema akrega seotud e Eventivali sisse logimiseks kasutatud e-mail?
